### ISSUE TITLE
Function Request

### ISSUE THREAD

**Issue by synaomen** [Quicksilver666/jucy#3]
Moin,

wäre es möglich 2 Funktionen zu integrieren?
1. "Dont download 0 Byte Files"
2. "Dont download Files there are already in Share"

**Comment by Quicksilver666** [comment]
Bitte Feature requests ins Jucy forum unter https://jucy.eu/forum

Aber warum gibt es das nicht.
Beide Optionen verursachen Probleme denen sich viele User nicht bewusst
sind.
1. 0 Byte Files sind potentiell auch wichtige Dateien. Ein Programm kann
   z.B. auf Vorhandensein dieser Testen und nicht auf den Inhalt schauen.
2. stellt ein Problem dar da z.B. für Info Dateien für Releasegruppen.
   Wenn diese mehrfach gleich vorkommen läd man die nur einmal herunter und
   hat dann nur noch unvollständige releases sobald man mehrere Releases
   von der Selben Gruppe hat.
   Als Abhilfe gibt es die Färbung für Dateien... damit man nicht aus
   versehen Dateien herunterlädt die man bereits hat.
   Falls man eine Datei schon besitzt Kopiert Jucy diese nur Lokal auf der
   Festplatte man verliert also auch keine Bandweite.

Gruß**

Am 03/06/2015 um 02:05 schrieb Maik:

**Comment by synaomen** [comment]
> Bitte Feature requests ins Jucy forum unter https://jucy.eu/forum 

Das würde ich ja gerne tuhen, kann mir dort leider keinen Account erstellen, getestet mit Iceweasel v38.0.1 "You did not provide the correct code for the spam prevention check. Please try again.", habe aber keinen Chapta abfrage gesehen, Chromium und Vivaldi erkennen das Cert nicht an  "This server could not prove that is jucy.eu; its security certificate is not trusted by your computer´ s operating system", Konqueror hat mir das Chapta gezeigt, und danach kommt "Could not open socket" und auch wieder keinen Antwortmail.

Wenn möglich bitte schicke mir Zugangsdaten an forum856-forum@yahoo.de, selbe Nick wie hier. 
Dann werde ich dort die sachen re-posten.....

Gruß Syna

**Comment by Quicksilver666** [comment]
Das ist schade.
Es handelt sich um ein selbstsigniertes Zertifikat das sollte dennoch
Funktionieren/importierbar sein.
Es ist also nötig das im Browser selbst zu erlauben.

Beim Captcha nicht angezeigt werden handelt es sich scheinbar um ein
Problem das mir Wochenlang nicht aufgefallen ist.
Sollte nun funktionieren.

Danke!

Am 05/06/2015 um 15:00 schrieb Maik:

**Comment by synaomen** [comment]
Danke geht wieder....
